import { equipamentoFromImportRow } from "@/lib/equipamento-map";
import type { Prisma } from "@/generated/prisma/client";

type EquipamentoOrcamento = {
  nome: string;
  quantidade: number;
  descricao: string;
  setor: string;
  requisitos_minimos: string;
  valor_unitario_orcado: number | null;
  valor_total_orcado: number | null;
  previsao_aquisicao: 2026 | 2027;
  justificativa: string;
};

const EQUIPAMENTOS_ORCAMENTO: EquipamentoOrcamento[] = [
  {
    nome: "Aparelho de Hemodinâmica",
    quantidade: 1,
    descricao: "Equipamento para realização de procedimentos hemodinâmicos invasivos e diagnósticos cardiovasculares.",
    setor: "Hemodinâmica",
    requisitos_minimos: "Mesa angiográfica · Detector de painel plano · Injetor de contraste · Compatível com rede DICOM",
    valor_unitario_orcado: 2640000,
    valor_total_orcado: 2640000,
    previsao_aquisicao: 2026,
    justificativa: "Possível substituição do aparelho instalado no hospital.",
  },
  {
    nome: "Tomógrafo 64 Canais",
    quantidade: 1,
    descricao: "Tomógrafo computadorizado de 64 canais para diagnóstico por imagem.",
    setor: "Tomografia",
    requisitos_minimos: "64 canais · Gantry ≥ 70 cm · Reconstrução multiplanar · DICOM 3.0",
    valor_unitario_orcado: 2145000,
    valor_total_orcado: 2145000,
    previsao_aquisicao: 2026,
    justificativa: "Atualização tecnológica.",
  },
  {
    nome: "Bomba de Infusão Volumétrica",
    quantidade: 1,
    descricao: "Bomba de infusão para administração controlada de contraste na TC 2.",
    setor: "Tomografia 2",
    requisitos_minimos: "Controle de fluxo · Alarmes · Compatível com contraste iodado",
    valor_unitario_orcado: 160000,
    valor_total_orcado: 160000,
    previsao_aquisicao: 2026,
    justificativa: "Reforço operacional - aplicação de contrastes na TC 2.",
  },
  {
    nome: "Ultrassom Samsung S40",
    quantidade: 1,
    descricao: "Equipamento de ultrassonografia para diagnóstico por imagem.",
    setor: "Ultrassonografia",
    requisitos_minimos: "Transdutor convexo e linear · Doppler colorido · Tela ≥ 15\" · Armazenamento DICOM",
    valor_unitario_orcado: 170000,
    valor_total_orcado: 170000,
    previsao_aquisicao: 2026,
    justificativa: "Expansão diagnóstica, substituindo modelo Siemens de baixa adesão.",
  },
  {
    nome: "Aparelho de Anestesia para RM",
    quantidade: 1,
    descricao: "Equipamento de anestesia compatível com ambiente de ressonância magnética.",
    setor: "RNM",
    requisitos_minimos: "Compatível com RM (MRI-safe) · Vaporizador calibrado · Ventilador integrado · Modelo SAT MRI / KTK",
    valor_unitario_orcado: 283690,
    valor_total_orcado: 283690,
    previsao_aquisicao: 2026,
    justificativa: "Aumento das sedações na RNM. Equipamento previsto desde a instalação; compra postergada por descontinuação.",
  },
  {
    nome: "Raio-X Portátil",
    quantidade: 1,
    descricao: "Equipamento de raio-x portátil para uso à beira do leito.",
    setor: "Unidades de Internação",
    requisitos_minimos: "Detector digital portátil · Bateria autônoma · Interface DICOM · Manejo sem ferramentas",
    valor_unitario_orcado: 175000,
    valor_total_orcado: 175000,
    previsao_aquisicao: 2026,
    justificativa: "Substituição do equipamento obsoleto, sem possibilidade de conserto.",
  },
  {
    nome: "Carrinho Beira Leito com 6 Gavetas",
    quantidade: 2,
    descricao: "Carrinho com gavetas para apoio assistencial à beira do leito.",
    setor: "UTI / Ala Clínica",
    requisitos_minimos: "6 gavetas · Rodízios com trava · Tampo lavável · Estrutura em aço inox ou ABS",
    valor_unitario_orcado: null,
    valor_total_orcado: null,
    previsao_aquisicao: 2026,
    justificativa: "1 unidade para back-up (leitos reversíveis) e 1 para ala clínica.",
  },
  {
    nome: "Fototerapia Bilitron Sky 5006 - Fanem",
    quantidade: 2,
    descricao: "Equipamento de fototerapia neonatal de alta intensidade.",
    setor: "UTI Neonatal e Pediátrica",
    requisitos_minimos: "LEDs de alta intensidade · Irradiância ≥ 30 µW/cm²/nm · Timer integrado · Marca Fanem",
    valor_unitario_orcado: 14000,
    valor_total_orcado: 28000,
    previsao_aquisicao: 2026,
    justificativa: "Substituição de equipamentos ultrapassados.",
  },
  {
    nome: "Incubadora Neonatal 1186C - Fanem",
    quantidade: 6,
    descricao: "Incubadora neonatal para cuidados intensivos.",
    setor: "UTI Neonatal e Pediátrica",
    requisitos_minimos: "Controle de temperatura e umidade · Servo-controle · Acesso lateral · Trade-in disponível - Marca Fanem",
    valor_unitario_orcado: 39000,
    valor_total_orcado: 234000,
    previsao_aquisicao: 2026,
    justificativa: "Defeitos recorrentes; renovação do parque. Valor com trade-in (normal R$ 58.000).",
  },
  {
    nome: "Bilirrubinômetro Transcutâneo (Bilichek)",
    quantidade: 1,
    descricao: "Bilirrubinômetro transcutâneo não invasivo para recém-nascidos.",
    setor: "UTI Neonatal e Pediátrica",
    requisitos_minimos: "Medição transcutânea não invasiva · Faixa neonatal · Memória de medições",
    valor_unitario_orcado: 37000,
    valor_total_orcado: 37000,
    previsao_aquisicao: 2026,
    justificativa: "Bilirrubinômetro transcutâneo para UTI Neonatal.",
  },
  {
    nome: "Ultrassom Portátil V Scan Air CL GE",
    quantidade: 1,
    descricao: "Ultrassom portátil point-of-care para uso em urgência e UTIs.",
    setor: "UTI / Unidade de Emergência",
    requisitos_minimos: "Portátil · Doppler colorido · Conectividade wireless · Sonda phased array e linear",
    valor_unitario_orcado: 39000,
    valor_total_orcado: 39000,
    previsao_aquisicao: 2026,
    justificativa: "Visualização rápida para agilizar tomada de decisão em urgências e UTIs.",
  },
  {
    nome: "Manequim Bissexual Adulto com Órgãos",
    quantidade: 1,
    descricao: "Manequim de treinamento adulto bissexual com órgãos internos removíveis.",
    setor: "Educação Corporativa",
    requisitos_minimos: "Órgãos internos removíveis · Adulto · Bissexual · Material anatômico realista",
    valor_unitario_orcado: 4100,
    valor_total_orcado: 4100,
    previsao_aquisicao: 2026,
    justificativa: "Treinamento de educação corporativa.",
  },
  {
    nome: "Manequim Bissexual Infantil (3-5 anos) com Órgãos",
    quantidade: 1,
    descricao: "Manequim de treinamento infantil (3-5 anos) com órgãos internos removíveis.",
    setor: "Educação Corporativa",
    requisitos_minimos: "Órgãos internos removíveis · Infantil 3-5 anos · Bissexual · Material anatômico realista",
    valor_unitario_orcado: 6600,
    valor_total_orcado: 6600,
    previsao_aquisicao: 2026,
    justificativa: "Treinamento de educação corporativa.",
  },
  {
    nome: "Cardioversor Elétrico",
    quantidade: 1,
    descricao: "Cardioversor elétrico para cardioversão e desfibrilação.",
    setor: "Unidade 1",
    requisitos_minimos: "Desfibrilação bifásica · Modo sincronizado · ECG integrado · Portátil",
    valor_unitario_orcado: 28000,
    valor_total_orcado: 28000,
    previsao_aquisicao: 2026,
    justificativa: "Suprir a unidade que compartilha equipamento com a pediatria.",
  },
  {
    nome: "Aparelho de Anestesia Drager",
    quantidade: 1,
    descricao: "Aparelho de anestesia para uso em centro cirúrgico.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "Ventilador integrado · Vaporizadores calibrados · Monitoramento de gases · Marca Drager",
    valor_unitario_orcado: 170000,
    valor_total_orcado: 170000,
    previsao_aquisicao: 2026,
    justificativa: "Necessidade do centro cirúrgico.",
  },
  {
    nome: "Insufladora Laparoscópica",
    quantidade: 1,
    descricao: "Insufladora para procedimentos laparoscópicos.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "Fluxo regulável · Display digital de pressão · Filtro HEPA · Substituição de equipamento antigo",
    valor_unitario_orcado: 85000,
    valor_total_orcado: 85000,
    previsao_aquisicao: 2026,
    justificativa: "Substituição do equipamento atual.",
  },
  {
    nome: "Colonoscópio Olympus CF-H170L",
    quantidade: 1,
    descricao: "Colonoscópio para exames endoscópicos do cólon.",
    setor: "Endoscopia",
    requisitos_minimos: "Compatível com processadora Olympus · Alta definição · Canal de trabalho ≥ 3,7 mm",
    valor_unitario_orcado: null,
    valor_total_orcado: 102000,
    previsao_aquisicao: 2026,
    justificativa: "Renovação e ampliação do parque de endoscopia.",
  },
  {
    nome: "Endoscópio Olympus GIF-Q170",
    quantidade: 1,
    descricao: "Endoscópio para exames do trato digestivo superior.",
    setor: "Endoscopia",
    requisitos_minimos: "Compatível com processadora Olympus · Alta definição · Canal de trabalho ≥ 2,8 mm",
    valor_unitario_orcado: null,
    valor_total_orcado: 98000,
    previsao_aquisicao: 2026,
    justificativa: "Renovação e ampliação do parque de endoscopia.",
  },
  {
    nome: "Bomba de Irrigação para Endoscopia",
    quantidade: 1,
    descricao: "Bomba de irrigação para procedimentos endoscópicos.",
    setor: "Endoscopia",
    requisitos_minimos: "Fluxo regulável · Compatível com endoscópios Olympus · Parcelamento em 10x",
    valor_unitario_orcado: 23000,
    valor_total_orcado: 23000,
    previsao_aquisicao: 2026,
    justificativa: "Parcelado em 10 vezes.",
  },
  {
    nome: "Monitor Multiparâmetros - CC (Drager)",
    quantidade: 2,
    descricao: "Monitor multiparâmetros para salas cirúrgicas principais.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "ECG · SpO2 · PNI · Temperatura · IBP · Compatível Drager Infinity Delta · Conectividade",
    valor_unitario_orcado: 42000,
    valor_total_orcado: 84000,
    previsao_aquisicao: 2026,
    justificativa: "Projeto de integração - substituição para compatibilidade (Drager).",
  },
  {
    nome: "Monitor Multiparâmetros - CC Ambulatorial",
    quantidade: 1,
    descricao: "Monitor multiparâmetros para centro cirúrgico ambulatorial.",
    setor: "Centro Cirúrgico Ambulatorial",
    requisitos_minimos: "ECG · SpO2 · PNI · Temperatura · Conectividade · Projeto de integração",
    valor_unitario_orcado: 28000,
    valor_total_orcado: 28000,
    previsao_aquisicao: 2026,
    justificativa: "Projeto de integração - substituição para compatibilidade.",
  },
  {
    nome: "Monitor Multiparâmetros - CC 10A",
    quantidade: 7,
    descricao: "Monitor multiparâmetros para salas do Centro Cirúrgico 10A.",
    setor: "Centro Cirúrgico - 10A",
    requisitos_minimos: "ECG · SpO2 · PNI · Temperatura · Conectividade · Projeto de integração",
    valor_unitario_orcado: 14000,
    valor_total_orcado: 98000,
    previsao_aquisicao: 2026,
    justificativa: "Projeto de integração - substituição para compatibilidade (7 unidades).",
  },
  {
    nome: "Projeto de Proteção Coletiva - Trabalho em Altura",
    quantidade: 1,
    descricao: "Projeto e execução de proteção coletiva para trabalho em altura no telado.",
    setor: "Hospital (Infraestrutura)",
    requisitos_minimos: "Conforme NR-35 · Guarda-corpo · Linha de vida · Execução: Sol Engenharia e Construção",
    valor_unitario_orcado: 175000,
    valor_total_orcado: 175000,
    previsao_aquisicao: 2026,
    justificativa: "Segurança ocupacional em alturas (telado) - solicitação crítica.",
  },
  {
    nome: "Instalação SPDA - Modelo Gaiola (Para-raios)",
    quantidade: 1,
    descricao: "Instalação de sistema de proteção contra descargas atmosféricas no prédio.",
    setor: "Hospital (Infraestrutura)",
    requisitos_minimos: "Modelo gaiola de Faraday · Conforme NBR 5419 · Laudo ART",
    valor_unitario_orcado: 390000,
    valor_total_orcado: 390000,
    previsao_aquisicao: 2026,
    justificativa: "Proteção contra raios no prédio atual.",
  },
  {
    nome: "Bilitron Bed - Berçário",
    quantidade: 2,
    descricao: "Equipamento de fototerapia em berço para tratamento de icterícia neonatal.",
    setor: "Berçário",
    requisitos_minimos: "LEDs azuis de alta intensidade · Berço integrado · Timer · Irradiância controlada",
    valor_unitario_orcado: 26000,
    valor_total_orcado: 52000,
    previsao_aquisicao: 2027,
    justificativa: "Tratamento de icterícia neonatal.",
  },
  {
    nome: "Venoscópio",
    quantidade: 1,
    descricao: "Equipamento para visualização de veias para punção venosa pediátrica.",
    setor: "Pediatria",
    requisitos_minimos: "Projeção de imagem venosa · Portátil · Luz infravermelho · Uso pediátrico",
    valor_unitario_orcado: 42000,
    valor_total_orcado: 42000,
    previsao_aquisicao: 2027,
    justificativa: "Facilitar acesso venoso em pediatria.",
  },
  {
    nome: "Ultrassom Point of Care - Lumify Philips",
    quantidade: 1,
    descricao: "Ultrassom portátil point-of-care para punções de difícil acesso.",
    setor: "Pediatria",
    requisitos_minimos: "Portátil · App Lumify · Sonda linear · Conecta ao smartphone/tablet · Philips",
    valor_unitario_orcado: 39000,
    valor_total_orcado: 39000,
    previsao_aquisicao: 2027,
    justificativa: "Melhorar punções de difícil acesso; equipe em treinamento.",
  },
  {
    nome: "Cama Hospitalar Elétrica",
    quantidade: 42,
    descricao: "Cama hospitalar com acionamento elétrico e regulagem de posição.",
    setor: "Unidades de Internação",
    requisitos_minimos: "Ajuste elétrico de altura e posição · Grades laterais · Rodízios com trava · End of service",
    valor_unitario_orcado: 14000,
    valor_total_orcado: 588000,
    previsao_aquisicao: 2027,
    justificativa: "End of Service: 14 pediatria, 16 maternidade, 10 clínica, 2 ala 2.",
  },
  {
    nome: "Monitor de Sinais Vitais - Baxter MEWS/PILS",
    quantidade: 2,
    descricao: "Monitor de sinais vitais com PNI, SpO2, termometria e conectividade.",
    setor: "Unidades de Internação",
    requisitos_minimos: "PNI · SpO2 Nellcor · Termometria SureTemp® · Conectividade cabo/Wi-Fi · MEWS/PILS Baxter",
    valor_unitario_orcado: 19600,
    valor_total_orcado: 39200,
    previsao_aquisicao: 2027,
    justificativa: "Integração MEWS, PILS (Baxter).",
  },
  {
    nome: "Carrinho Clínico Móvel Welch Allyn",
    quantidade: 2,
    descricao: "Carrinho clínico móvel para transporte de equipamentos de avaliação.",
    setor: "Unidades de Internação / Enfermagem",
    requisitos_minimos: "Rodízios com trava · Suporte para equipamentos Welch Allyn · Estrutura robusta",
    valor_unitario_orcado: 2900,
    valor_total_orcado: 5800,
    previsao_aquisicao: 2027,
    justificativa: "Integração MEWS, PILS (Baxter).",
  },
  {
    nome: "Monitor Multiparâmetros - Internação",
    quantidade: 8,
    descricao: "Monitores multiparâmetros para leitos de internação e maternidade.",
    setor: "Unidades de Internação",
    requisitos_minimos: "ECG · SpO2 · PNI · Temperatura · Conectividade · Atendimento obstétrico",
    valor_unitario_orcado: 14000,
    valor_total_orcado: 112000,
    previsao_aquisicao: 2027,
    justificativa: "Padronização e atendimento obstétrico na maternidade.",
  },
  {
    nome: "Unidade Híbrida UTI Neonatal - Fanem Dueto 2386",
    quantidade: 1,
    descricao: "Unidade híbrida de cuidado intensivo neonatal (incubadora + berço aquecido).",
    setor: "UTI Neonatal e Pediátrica",
    requisitos_minimos: "Modo incubadora e berço aquecido · Servo-controle · Balança integrada · Marca Fanem Dueto 2386",
    valor_unitario_orcado: 141794,
    valor_total_orcado: 141794,
    previsao_aquisicao: 2027,
    justificativa: "Planilha original previa 3; já adquirida 1; esta é a 2ª restante.",
  },
  {
    nome: "Sistema de Hipotermia Terapêutica",
    quantidade: 1,
    descricao: "Sistema de hipotermia para tratamento de encefalopatia hipóxico-isquêmica neonatal.",
    setor: "UTI Neonatal e Pediátrica",
    requisitos_minimos: "Controle de temperatura ±0,5°C · Cobertor/colchão · Alarmes · Uso neonatal",
    valor_unitario_orcado: 275000,
    valor_total_orcado: 275000,
    previsao_aquisicao: 2027,
    justificativa: "Necessidade clínica da UTI Neonatal.",
  },
  {
    nome: "Monitor de Débito Cardíaco",
    quantidade: 1,
    descricao: "Monitor de débito cardíaco para monitorização hemodinâmica avançada.",
    setor: "UTI Adulto I",
    requisitos_minimos: "Termodiluição ou PiCCO · Parâmetros hemodinâmicos avançados · Alarmes",
    valor_unitario_orcado: 36000,
    valor_total_orcado: 36000,
    previsao_aquisicao: 2027,
    justificativa: "Atender requisitos normativos da UTI Adulto.",
  },
  {
    nome: "Bipap",
    quantidade: 2,
    descricao: "Ventilador não invasivo para suporte respiratório com pressão positiva bifásica.",
    setor: "UTI 2",
    requisitos_minimos: "Modo CPAP e BiPAP · Máscara inclusa · Alarmes · Interface paciente adulto/pediátrico",
    valor_unitario_orcado: 9000,
    valor_total_orcado: 18000,
    previsao_aquisicao: 2027,
    justificativa: "Necessidade da UTI 2.",
  },
  {
    nome: "Monitor Cardíaco para Transporte",
    quantidade: 1,
    descricao: "Monitor cardíaco portátil para transporte de pacientes graves.",
    setor: "Unidade de Emergência",
    requisitos_minimos: "ECG · SpO2 · PNI · Bateria autônoma ≥ 4h · Portátil e resistente",
    valor_unitario_orcado: 16000,
    valor_total_orcado: 16000,
    previsao_aquisicao: 2027,
    justificativa: "Minimizar riscos no transporte de pacientes graves.",
  },
  {
    nome: "Monitor para Leitos da Sala de Emergência",
    quantidade: 1,
    descricao: "Monitor multiparâmetros para leitos da sala de emergência com integração ao sistema.",
    setor: "Unidade de Emergência",
    requisitos_minimos: "ECG · SpO2 · PNI · Temperatura · Integração com sistema HIS · Conectividade",
    valor_unitario_orcado: 28000,
    valor_total_orcado: 28000,
    previsao_aquisicao: 2027,
    justificativa: "Substituição dos monitores comprometidos pelo tempo de uso; integração com sistema.",
  },
  {
    nome: "Berços com Grade - Emergência",
    quantidade: 4,
    descricao: "Berços hospitalares com grade para uso na unidade de emergência.",
    setor: "Unidade de Emergência",
    requisitos_minimos: "Grades laterais · Rodízios com trava · Material lavável · Substituição dos danificados",
    valor_unitario_orcado: 21000,
    valor_total_orcado: 84000,
    previsao_aquisicao: 2027,
    justificativa: "Substituição dos berços danificados e sem condições de manutenção.",
  },
  {
    nome: "Mantas Térmicas (Colchão) - CC",
    quantidade: 2,
    descricao: "Colchões/mantas térmicas para controle de temperatura em procedimentos cirúrgicos.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "Aquecimento por ar forçado ou água · Cobertura corporal · Descartável ou reutilizável",
    valor_unitario_orcado: 1900,
    valor_total_orcado: 3800,
    previsao_aquisicao: 2027,
    justificativa: "Movimentação entre salas cirúrgicas.",
  },
  {
    nome: "Botas Pneumáticas - CC",
    quantidade: 2,
    descricao: "Botas pneumáticas para profilaxia de trombose venosa profunda em cirurgias.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "Compressão pneumática sequencial · Tamanhos P/M/G · Apoio anestésico",
    valor_unitario_orcado: 6800,
    valor_total_orcado: 13600,
    previsao_aquisicao: 2027,
    justificativa: "Apoio anestésico no centro cirúrgico.",
  },
  {
    nome: "Mesa Cirúrgica Radiotransparente",
    quantidade: 1,
    descricao: "Mesa cirúrgica radiotransparente para procedimentos com fluoroscopia.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "Tampo radiotransparente · Ajuste elétrico multiposição · Capacidade ≥ 200 kg · Substituição das antigas",
    valor_unitario_orcado: 74000,
    valor_total_orcado: 74000,
    previsao_aquisicao: 2027,
    justificativa: "Substituição das mesas antigas com defeito.",
  },
  {
    nome: "Foco Auxiliar Cirúrgico",
    quantidade: 1,
    descricao: "Foco de iluminação auxiliar para salas cirúrgicas.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "LED · Ajuste de intensidade · Braço articulado · Iluminação sem sombra",
    valor_unitario_orcado: null,
    valor_total_orcado: 24000,
    previsao_aquisicao: 2027,
    justificativa: "Demanda de iluminação adicional no CC.",
  },
  {
    nome: "Gabinete de Aquecimento de Soro",
    quantidade: 1,
    descricao: "Gabinete para aquecimento de soluções parenterais.",
    setor: "Centro Cirúrgico",
    requisitos_minimos: "Temperatura regulável 37-42°C · Capacidade ≥ 20 L · Alarme de temperatura",
    valor_unitario_orcado: null,
    valor_total_orcado: 8000,
    previsao_aquisicao: 2027,
    justificativa: "Protocolo de prevenção de hipotermia.",
  },
  {
    nome: "Caixas de Cesárea Novas (CME)",
    quantidade: 2,
    descricao: "Caixas cirúrgicas completas para procedimentos de cesárea.",
    setor: "CME",
    requisitos_minimos: "Aço inox AISI 316L · Compatível com autoclave · Peças padronizadas · Renovação",
    valor_unitario_orcado: 4481,
    valor_total_orcado: 8962,
    previsao_aquisicao: 2027,
    justificativa: "Renovação do parque de caixas cirúrgicas.",
  },
  {
    nome: "Caixas de Peças de Cesárea - 36 peças (CME)",
    quantidade: 8,
    descricao: "Caixas de reposição de peças para cesárea com 36 peças cada.",
    setor: "CME",
    requisitos_minimos: "36 peças por caixa · Aço inox · Esterilizável · Manutenção do parque",
    valor_unitario_orcado: 5825.3,
    valor_total_orcado: 46602.4,
    previsao_aquisicao: 2027,
    justificativa: "Manutenção do parque cirúrgico.",
  },
  {
    nome: "Bandejas de Vídeo Colecistectomia (CME)",
    quantidade: 2,
    descricao: "Bandejas cirúrgicas para procedimentos de colecistectomia videolaparoscópica.",
    setor: "CME",
    requisitos_minimos: "Instrumental completo para laparoscopia · Aço inox · Compatível com autoclave",
    valor_unitario_orcado: 23188,
    valor_total_orcado: 46376,
    previsao_aquisicao: 2027,
    justificativa: "Suprir urgências de colecistectomia.",
  },
  {
    nome: "Kits Simples - 13 peças (CME)",
    quantidade: 10,
    descricao: "Kits cirúrgicos simples para cirurgias de baixa complexidade.",
    setor: "CME",
    requisitos_minimos: "13 peças por kit · Aço inox · Esterilizável · Cirurgias de baixa complexidade",
    valor_unitario_orcado: null,
    valor_total_orcado: 75000,
    previsao_aquisicao: 2027,
    justificativa: "Cirurgias de baixa complexidade.",
  },
  {
    nome: "Perfurador de Mão a Bateria Stryker",
    quantidade: 2,
    descricao: "Perfurador ortopédico a bateria para uso em centro cirúrgico.",
    setor: "CME / Centro Cirúrgico",
    requisitos_minimos: "Bateria recarregável · Velocidade variável · Marca Stryker · Renovação de parque",
    valor_unitario_orcado: 155000,
    valor_total_orcado: 310000,
    previsao_aquisicao: 2027,
    justificativa: "Renovação do parque de perfuradores.",
  },
  {
    nome: "Kit de Pistolas Atemo - Endoscopia",
    quantidade: 1,
    descricao: "Kit de pistolas para higienização de endoscópios.",
    setor: "Endoscopia",
    requisitos_minimos: "Compatível com equipamentos Olympus · Kit completo · Higienização de canais",
    valor_unitario_orcado: 4800,
    valor_total_orcado: 4800,
    previsao_aquisicao: 2027,
    justificativa: "Falta em uma das salas de higienização.",
  },
  {
    nome: "Seladora de Pedal com Temporizador 60cm - Rouparia",
    quantidade: 1,
    descricao: "Seladora de pedal com temporizador para embalagem de rouparia hospitalar.",
    setor: "Rouparia",
    requisitos_minimos: "Selagem a quente · Temporizador · Largura 60 cm · Substituição da atual com defeito",
    valor_unitario_orcado: 1800,
    valor_total_orcado: 1800,
    previsao_aquisicao: 2027,
    justificativa: "Substituição da seladora com problemas frequentes.",
  },
  {
    nome: "Máquina de Costura Overlock Singer",
    quantidade: 1,
    descricao: "Máquina de costura overlock para manutenção de rouparia hospitalar.",
    setor: "Rouparia",
    requisitos_minimos: "4 a 6 tipos de ponto · Marca Singer · Substituição - sem peças disponíveis para conserto",
    valor_unitario_orcado: 4000,
    valor_total_orcado: 4000,
    previsao_aquisicao: 2027,
    justificativa: "Substituição - sem peças para conserto do equipamento atual.",
  },
  {
    nome: "Pacote de Software Philips - CDC Sala 3",
    quantidade: 1,
    descricao: "Atualização de software para aparelho Philips da sala 3 do CDC.",
    setor: "CDC",
    requisitos_minimos: "Compatível com aparelho Philips sala 3 · Atualização de versão · Licença incluída",
    valor_unitario_orcado: 65000,
    valor_total_orcado: 65000,
    previsao_aquisicao: 2027,
    justificativa: "Atualização do software do aparelho.",
  },
  {
    nome: "Sonda para Ecocardiografia Transesofágica",
    quantidade: 1,
    descricao: "Sonda para realização de ecocardiograma transesofágico.",
    setor: "CDC",
    requisitos_minimos: "Compatível com equipamento Philips do setor · Multiplanar · Segunda sonda do setor",
    valor_unitario_orcado: 154000,
    valor_total_orcado: 154000,
    previsao_aquisicao: 2027,
    justificativa: "Necessidade de segunda sonda para o CDC.",
  },
  {
    nome: "Transdutor Portátil POCUS - CDC",
    quantidade: 1,
    descricao: "Transdutor portátil para realização de POCUS beira leito.",
    setor: "CDC",
    requisitos_minimos: "Portátil · Point of Care · Conectividade wireless ou USB · Uso beira leito",
    valor_unitario_orcado: 39000,
    valor_total_orcado: 39000,
    previsao_aquisicao: 2027,
    justificativa: "Ultrassom portátil point of care beira leito.",
  },
  {
    nome: "Monitor Multiparâmetros - UTI Infantil 8 (substituição interna)",
    quantidade: 2,
    descricao: "Monitor multiparâmetros para UTI Infantil - substituição interna por compatibilidade.",
    setor: "UTI Infantil - 8",
    requisitos_minimos: "ECG · SpO2 · PNI · Conectividade · Compatibilidade com projeto de integração · Substituição interna",
    valor_unitario_orcado: 0,
    valor_total_orcado: 0,
    previsao_aquisicao: 2027,
    justificativa: "Projeto de integração - substituição interna (equipamentos virão do CC).",
  },
];

function categoriaPorSetor(setor: string) {
  if (setor.includes("Infraestrutura")) return "Infraestrutura";
  if (setor === "CME" || setor.includes("CME")) return "Instrumentais cirúrgicos";
  if (setor.includes("Rouparia")) return "Apoio operacional";
  if (setor.includes("Educação")) return "Treinamento";
  if (setor.includes("CDC")) return "Diagnóstico";
  return "Equipamentos hospitalares";
}

function tipoPorNome(nome: string) {
  const lower = nome.toLowerCase();
  if (lower.includes("software")) return "software";
  if (lower.includes("projeto") || lower.includes("instalação")) return "servico";
  if (lower.includes("cama") || lower.includes("carrinho") || lower.includes("berço")) return "mobiliario";
  if (lower.includes("caixas") || lower.includes("bandejas") || lower.includes("kits")) return "instrumental";
  return "equipamento";
}

function criticidadePorItem(item: EquipamentoOrcamento) {
  if (item.valor_unitario_orcado === 0) return "baixa";
  if (item.previsao_aquisicao === 2026) return "alta";
  if (item.setor.includes("UTI") || item.setor.includes("Emergência") || item.setor.includes("Centro Cirúrgico")) {
    return "alta";
  }
  return "média";
}

/** Linhas do catálogo oficial (formato enriquecido do convite). */
export const CATALOGO_EQUIPAMENTOS_OFICIAL = EQUIPAMENTOS_ORCAMENTO.map((item, index) => ({
  id: `eq_${String(index + 1).padStart(3, "0")}`,
  nome_original: item.nome,
  nome_padronizado: item.nome,
  tipo: tipoPorNome(item.nome),
  categoria: categoriaPorSetor(item.setor),
  subcategoria: String(item.previsao_aquisicao),
  setor_hospitalar: item.setor,
  anvisa_classe: "",
  criticidade: criticidadePorItem(item),
  descricao_editavel: item.descricao,
  requisitos_minimos: item.requisitos_minimos.split(" · "),
  quantidade: item.quantidade,
  valor_estimado: item.valor_unitario_orcado,
  valor_total_orcado: item.valor_total_orcado,
  previsao_aquisicao: item.previsao_aquisicao,
  justificativa: item.justificativa,
}));

/** Seed genérico para hospitais que não são o catálogo demo (retrocompatível). */
export const SEED_EQUIPAMENTOS_GENERICOS = [
  {
    nome: "Monitor multiparamétrico",
    descricao: "Monitor de sinais vitais com PNI e SpO2.",
    quantidade: 10,
    categoria: "Monitoramento",
    criticidade: "alta",
  },
  {
    nome: "Bomba de infusão volumétrica",
    descricao: "Bomba com biblioteca de medicamentos e alarmes.",
    quantidade: 25,
    categoria: "Infusão",
    criticidade: "alta",
  },
  {
    nome: "Cama hospitalar elétrica",
    descricao: "Cama com acionamento elétrico e grades.",
    quantidade: 5,
    categoria: "Leitos",
    criticidade: "média",
  },
] as const;

export function dadosCatalogoCreateMany(hospitalId: string): Prisma.EquipamentoCreateManyInput[] {
  return CATALOGO_EQUIPAMENTOS_OFICIAL.map((row) =>
    equipamentoFromImportRow(row as unknown as Record<string, unknown>, hospitalId),
  );
}
